### PR TITLE
chore: upgrade dependencies

### PR DESCRIPTION
**Pull request by XiNiHa**
- ESLint is excluded from major bump since typescript-eslint v8 that supports ESLint v9 is still not released as stable.

### CODE REVIEW

**Review by tonyfromundefined — CHANGES_REQUESTED** [review]
Hello @XiNiHa! `.nvmrc` is currently set to version 16, but it seems like this part is out of sync. After discussing it internally, we decided that it would be better to delete `.nvmrc`. Could you please apply that part?

**Comment by XiNiHa** [comment]
Done! BTW, while removing the Node 16 requirement, I also updated CONTRIBUTING.md to state that only maintained Node versions are supported. Therefore it should be confirmed whether that matches what other maintainers are also thinking about.

**Review by tonyfromundefined — APPROVED** [review]
LGTM

**Comment by tonyfromundefined** [comment]
FYI: VSCode 1.19.1 is required for TypeScript Language Service

**Comment by tonyfromundefined** [comment]
@XiNiHa A simple version bump happened and it caused a conflict. Can you resolve this conflict?

**Comment by XiNiHa** [comment]
@tonyfromundefined Done!

**Pull request merged**
